/**
 * @license Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

var CKBUILDER_CONFIG = {
	skin: 'bootstrapck',
	ignore: [
		'dev',
		'README.md',
		'.gitignore',
		'.gitattributes',
		'.idea',
		'.mailmap',
		'.DS_Store',
		'tests',
		'package.json',
		'bender.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'node_modules'
	],
	plugins: {
		a11yhelp: 1,
		about: 0,
		basicstyles: 1,
		bidi: 1,
		blockquote: 1,
		clipboard: 1,
		colorbutton: 1,
		colordialog: 1,
		contextmenu: 1,
		dialogadvtab: 1,
		div: 1,
		elementspath: 1,
		enterkey: 1,
		entities: 1,
		filebrowser: 0,
		find: 1,
		flash: 0,
		floatingspace: 1,
		font: 1,
		format: 1,
		forms: 0,
		horizontalrule: 1,
		htmlwriter: 1,
		iframe: 1,
		indentlist: 1,
		indentblock: 1,
		justify: 1,
		link: 1,
		list: 1,
		liststyle: 1,
		magicline: 1,
		maximize: 1,
		newpage: 0,
		pagebreak: 0,
		pastefromword: 1,
		pastetext: 1,
		preview: 0,
		print: 0,
		removeformat: 1,
		resize: 1,
		save: 0,
		scayt: 1,
		selectall: 0,
		showblocks: 0,
		showborders: 0,
		smiley: 0,
		sourcearea: 1,
		specialchar: 1,
		stylescombo: 1,
		tab: 1,
		table: 0,
		tabletools: 0,
		templates: 0,
		toolbar: 1,
		undo: 1,
		wysiwygarea: 1,
		lineutils: 1,
		widget: 1,
		divarea: 1,
		oembed: 1,
		image3: 1
	}
};
